env:
  es2020: true
  browser: true

parserOptions:
  sourceType: module

extends:
  - 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
      ignoreComments: true
  linebreak-style:
    - off
  no-console:
    - off
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always

globals:
  sap: writable