#
## Application Properties
#

logger:
  format: ":date[iso] :method :url :status :response-time msec :res[content-length] bytes"

server:
  port: 5000
  public: "public"    # location of static resources