env:
  es6: true     # needed to bring the globals such as Promise into scope
  node: true

parserOptions:
  ecmaVersion: 2018
  
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - off
  no-console:
    - off
  quotes:
    - error
    - single
    - allowTemplateLiterals: true    
  semi:
    - error
    - always
