env:
  es2021: true
  node: true

parserOptions:
  sourceType: module

extends:
  - 'eslint:recommended'

rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - off
  no-console:
    - off
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always