AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  sam-lambda-health-check

  Sample SAM Template for sam-lambda-health-check

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaHealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      DockerTag: latest
      DockerContext: ./lambda-health-check
      Dockerfile: Dockerfile

Outputs:
  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaHealthCheckFunction.Arn
  LambdaFunctionIamRole:
    Description: "Implicit IAM Role created for the Lambda function"
    Value: !GetAtt LambdaHealthCheckFunction.Arn
