---
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CloudFormation template that launches an EC2 instance that
  is configured with a security group that allows for inbound
  ICMP requests from any IP address, and inbound SSH access
  from a specific public IP address.


Parameters:
  KeyName:
    Description: 'Key Pair name'
    Type: 'AWS::EC2::KeyPair::KeyName'
  VPC:
    Description: 'VPC ID where the instance will be placed'
    Type: 'AWS::EC2::VPC::Id'
  Subnet:
    Description: 'Subnet ID where the instance will be placed'
    Type: 'AWS::EC2::Subnet::Id'
  IpForSSH:
    Description: 'Public IP address with SSH access to instance'
    Type: String
    AllowedPattern: '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
    ConstraintDescription: 'Enter a valid IPv4 address'

Mappings:
  RegionToAMIMap:
    # Including only three regions for demonstration purposes
    'us-east-1':
      AMI: 'ami-0915bcb5fa77e4892'

    'eu-central-1':
      AMI: 'ami-02f9ea74050d6f812'

    'ap-southeast-1':
      AMI: 'ami-0d06583a13678c938'

Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group allowing ICMP and SSH traffic'
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: 'Inbound-ICMP-SSH-SG'
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Sub '${IpForSSH}/32'
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [RegionToAMIMap, !Ref 'AWS::Region', AMI]
      InstanceType: 't2.micro'
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetId: !Ref Subnet
      Tags:
        - Key: Name
          Value: !Sub 'EC2 instance with SG'

Outputs:
  InstancePublicName:
    Value: !Sub ${Instance.PublicDnsName}
    Description: 'Public DNS name of the instance to connect with ec2-user'
