---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Spin up EC2 instance'
Parameters:
  KeyName:
    Description: 'Key Pair name'
    Type: 'AWS::EC2::KeyPair::KeyName'
  VPC:
    Description: 'VPC on which the VM will be placed'
    Type: 'AWS::EC2::VPC::Id'
  Subnet:
    Description: 'Subnet on which the VM will be placed'
    Type: 'AWS::EC2::Subnet::Id'
  InstanceType:
    Description: 'Select one instance type from the list'
    Type: String
    Default: 't2.micro'
    AllowedValues: ['t2.micro', 't2.small', 't2.medium']

Mappings:
  RegionMap:  # used to map region with the AmazonLinux image in that region
    # Including only three regions for the purpose of demonstrating mappings
    'us-east-1':
      AMI: 'ami-0915bcb5fa77e4892'

    'eu-central-1':
      AMI: 'ami-02f9ea74050d6f812'

    'ap-southeast-1':
      AMI: 'ami-0d06583a13678c938'

Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group for the VM'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0' # open to the world
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22

  VM:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI] # get the AMI from the Region Map
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: [!Ref SecurityGroup]
      SubnetId: !Ref Subnet

Outputs:
  PublicName:
    Value: !GetAtt 'VM.PublicDnsName'
    Description: 'Public DNS Name of the server to connect via SSH as user ec2-user'
